# Generated by Django 5.2 on 2025-05-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='experiencia',
            field=models.IntegerField(help_text='Tempo de experiência', null=True),
        ),
    ]
