# Generated by Django 5.2 on 2025-05-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_personal_experiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='altura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='objetivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
